packages:
  - 'packages/*'
  - 'scripts/*'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  husky: false
  lmdb: false
  msgpackr-extract: false
  oxc-resolver: false
  svelte-preprocess: false
  vue-demi: false

blockExoticSubdeps: true
dedupePeers: true
dedupePeerDependents: true
minimumReleaseAge: 10080
shellEmulator: true
trustPolicy: no-downgrade
