packages:
  - 'packages/*'
  - 'scripts/*'
  - 'examples/*'

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  core-js: true
  deasync: false
  esbuild: true
  fsevents: true
  husky: true
  lmdb: true
  msgpackr-extract: true
  oxc-resolver: true
  parcel-bundler: true
  svelte-preprocess: true
  vue-demi: true

linkWorkspacePackages: true

overrides:
  '@types/node': 25.2.1
  vue: 3.5.17
  yaml: 2.8.2

patchedDependencies:
  '@vue/test-utils@2.4.6': patches/@vue__test-utils@2.4.6.patch
