name: 'CI setup'
description: ''
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Ensure npm 11.5.1 or later for trusted publishing
      run: npm install -g npm@latest
      shell: bash

    - name: Install Dependencies
      run: pnpm install
      shell: bash
