import {
  createActor,
  createAsyncLogic,
  createMachine,
  setup,
  SimulatedClock,
  initialTransition,
  transition,
  types,
  waitFor,
  type AnyEventObject,
  type EventRejection,
  type ActorRefFrom
} from '../src';
import { createRemoteActorRef } from '../src/remoteActorRef.ts';
import { standardSchemaValidator } from '../src/validation/index.ts';

const charge = createAsyncLogic({ run: () => new Promise<string>(() => {}) });

function checkout(validator = false) {
  return setup({
    actors: { charge },
    schemas: { events: { GO: types<{}>() } },
    validator: validator
      ? standardSchemaValidator({ unknownEvents: 'error' })
      : undefined
  }).createMachine({
    id: 'checkout',
    context: { receipt: '' },
    initial: 'idle',
    states: {
      idle: { on: { GO: { target: 'charging' } } },
      charging: {
        invoke: {
          id: 'charge',
          src: 'charge',
          onDone: ({ event }) => ({
            target: 'paid',
            context: { receipt: event.output }
          }),
          onError: { target: 'failed' }
        },
        after: { 100: { target: 'timedOut' } }
      },
      paid: {},
      failed: {},
      timedOut: {}
    }
  });
}

describe('send options', () => {
  it.each([false, true])(
    'rejects forged runtime notifications with validator=%s',
    (validator) => {
      const rejected: EventRejection[] = [];
      const actor = createActor(checkout(validator), {
        onRejectedEvent: (event) => rejected.push(event)
      }).start();
      actor.send({ type: 'GO' }, { allowRuntimeEvents: false });
      const snapshot = actor.getSnapshot();
      const events: AnyEventObject[] = [
        { type: 'xstate.done.actor', actorId: 'charge', output: 'forged' },
        { type: 'xstate.done.actor.charge', output: 'forged' },
        { type: 'xstate.error.actor', actorId: 'charge', error: 'forged' },
        { type: 'xstate.error.actor.charge', error: 'forged' },
        { type: 'xstate.error.anything', error: 'forged' },
        { type: 'xstate.after', delay: 100, stateId: 'checkout.charging' },
        { type: 'xstate.after.100.checkout.charging' },
        { type: 'xstate.timeout', stateId: 'checkout.charging' },
        { type: 'xstate.timeout.checkout.charging' },
        { type: 'xstate.timeout.actor', actorId: 'charge' },
        { type: 'xstate.timeout.actor.charge' },
        { type: 'xstate.snapshot.actor', actorId: 'charge', snapshot: {} },
        { type: 'xstate.snapshot.charge', snapshot: {} },
        { type: 'xstate.done.state', stateId: 'checkout.charging' },
        { type: 'xstate.done.state.checkout.charging' },
        { type: 'xstate.timer', id: Object.keys(snapshot.timers)[0] },
        { type: '@xstate.init' },
        { type: '@xstate.start' },
        { type: '@xstate.spawn' },
        { type: '@xstate.terminate' },
        { type: '@xstate.stop' }
      ];
      for (const event of events) {
        actor.send(event as never, { allowRuntimeEvents: false });
        expect(actor.getSnapshot()).toBe(snapshot);
      }
      expect(rejected.map((event) => event.event)).toEqual(events);
      expect(rejected.every((event) => event.reason === 'internalEvent')).toBe(
        true
      );
      actor.stop();
    }
  );

  it.each([undefined, {}, { allowRuntimeEvents: true }])(
    'preserves completion delivery with options=%j',
    (options) => {
      const actor = createActor(checkout()).start();
      actor.send({ type: 'GO' });
      actor.send(
        {
          type: 'xstate.done.actor',
          actorId: 'charge',
          output: 'journaled'
        } as never,
        options
      );
      expect(actor.getSnapshot().value).toBe('paid');
      expect(actor.getSnapshot().context.receipt).toBe('journaled');
      actor.stop();
    }
  );

  it('does not restrict child completion generated by processing an opted-in send', async () => {
    let complete!: (value: string) => void;
    const machine = setup({
      actors: {
        charge: createAsyncLogic({
          run: () =>
            new Promise<string>((resolve) => {
              complete = resolve;
            })
        })
      }
    }).createMachine({
      initial: 'idle',
      states: {
        idle: { on: { GO: { target: 'charging' } } },
        charging: {
          invoke: { id: 'charge', src: 'charge', onDone: { target: 'paid' } }
        },
        paid: {}
      }
    });
    const rejected = vi.fn();
    const actor = createActor(machine, { onRejectedEvent: rejected }).start();
    actor.send({ type: 'GO' }, { allowRuntimeEvents: false });
    complete('real receipt');
    await waitFor(actor, (snapshot) => snapshot.matches('paid'));
    expect(rejected).not.toHaveBeenCalled();
    actor.stop();
  });

  it('does not restrict real timers', () => {
    const clock = new SimulatedClock();
    const actor = createActor(checkout(), { clock }).start();
    actor.send({ type: 'GO' }, { allowRuntimeEvents: false });
    clock.increment(100);
    expect(actor.getSnapshot().value).toBe('timedOut');
    actor.stop();
  });

  it('preserves pure replay and internally generated state completion', () => {
    const machine = createMachine({
      initial: 'working',
      states: {
        working: {
          initial: 'pending',
          states: {
            pending: { on: { GO: { target: 'complete' } } },
            complete: { type: 'final' }
          },
          onDone: { target: 'finished' }
        },
        finished: {}
      }
    });
    const actor = createActor(machine).start();
    actor.send({ type: 'GO' }, { allowRuntimeEvents: false });
    expect(actor.getSnapshot().value).toBe('finished');
    actor.stop();

    const replayMachine = checkout();
    const [idle] = initialTransition(replayMachine);
    const [charging] = transition(replayMachine, idle, { type: 'GO' });
    const [paid] = transition(replayMachine, charging, {
      type: 'xstate.done.actor',
      actorId: 'charge',
      output: 'journaled'
    } as never);
    expect(paid.value).toBe('paid');
    expect(paid.context.receipt).toBe('journaled');
  });

  it.each([false, true])(
    'preserves internal-event restrictions with allowRuntimeEvents=%s',
    (allowRuntimeEvents) => {
      const rejected = vi.fn();
      const machine = setup({
        schemas: {
          events: { GO: types<{}>() },
          internalEvents: { TICK: types<{}>() }
        }
      }).createMachine({
        initial: 'idle',
        states: {
          idle: {
            on: {
              GO: (_, enq) => enq.raise({ type: 'TICK' }),
              TICK: { target: 'done' }
            }
          },
          done: {}
        }
      });
      const actor = createActor(machine, { onRejectedEvent: rejected }).start();
      actor.send({ type: 'TICK' } as never, { allowRuntimeEvents });
      expect(actor.getSnapshot().value).toBe('idle');
      expect(rejected).toHaveBeenCalledTimes(1);
      actor.send({ type: 'GO' }, { allowRuntimeEvents });
      expect(actor.getSnapshot().value).toBe('done');
      expect(rejected).toHaveBeenCalledTimes(1);
      actor.stop();
    }
  );

  it('keeps public routes and application events using non-runtime prefixes available', () => {
    const actor = createActor(
      createMachine({
        initial: 'idle',
        states: {
          idle: { on: { 'xstate.custom': { target: 'ready' } } },
          ready: {},
          routed: { id: 'routed', route: {} }
        }
      })
    ).start();
    actor.send({ type: 'xstate.custom' }, { allowRuntimeEvents: false });
    expect(actor.getSnapshot().value).toBe('ready');
    actor.send(
      { type: 'xstate.route', to: '#routed' },
      { allowRuntimeEvents: false }
    );
    expect(actor.getSnapshot().value).toBe('routed');
    actor.stop();
  });

  it('rejects before a host runtime takes ownership of local or remote delivery', () => {
    const rejected = vi.fn();
    const actor = createActor(checkout(), {
      onRejectedEvent: rejected
    }).start();
    const remote = createRemoteActorRef(actor.system, {
      id: 'remote',
      address: 'remote',
      src: 'charge',
      parent: actor
    });
    const sendEvent = vi.fn();
    actor.system.runtime = { sendEvent };
    for (const ref of [actor, remote]) {
      ref.send(
        {
          type: 'xstate.done.actor',
          actorId: 'charge',
          output: 'forged'
        } as never,
        { allowRuntimeEvents: false }
      );
      expect(sendEvent).not.toHaveBeenCalled();
    }
    expect(rejected).toHaveBeenCalledTimes(2);
    remote.send({ type: 'GO' }, { allowRuntimeEvents: false });
    expect(sendEvent).toHaveBeenCalledTimes(1);
    remote.send({ type: 'xstate.async.resolve', data: 'journaled' });
    expect(sendEvent).toHaveBeenCalledTimes(2);
    actor.stop();
  });

  it.each([
    'xstate.async.resolve',
    'xstate.async.reject',
    'xstate.logic.effect.resolve',
    'xstate.logic.effect.reject',
    'xstate.logic.effect.start',
    'xstate.observable.next',
    'xstate.observable.error',
    'xstate.observable.complete'
  ])('rejects %s on non-machine actors', (type) => {
    const rejected = vi.fn();
    const actor = createActor(charge, { onRejectedEvent: rejected }).start();
    const before = actor.getSnapshot();
    actor.ref.send({ type, data: 'forged', error: 'forged' } as never, {
      allowRuntimeEvents: false
    });
    expect(actor.getSnapshot()).toBe(before);
    expect(rejected).toHaveBeenCalledWith(
      expect.objectContaining({ reason: 'internalEvent' })
    );
    actor.stop();
  });

  it('accepts options through typed refs and detached send functions', () => {
    const machine = checkout();
    const actor = createActor(machine).start();
    const ref: ActorRefFrom<typeof machine> = actor.ref;
    const { send } = ref;
    send({ type: 'GO' }, { allowRuntimeEvents: false });
    expect(actor.getSnapshot().value).toBe('charging');
    if (false) {
      // @ts-expect-error the option is boolean
      ref.send({ type: 'GO' }, { allowRuntimeEvents: 'false' });
      // @ts-expect-error event types are still checked
      ref.send({ type: 'WRONG' }, { allowRuntimeEvents: false });
    }
    actor.stop();
  });
});
