name: 'CI checks'
runs:
  using: 'composite'
  steps:
    - name: Build
      run: pnpm build
      shell: bash

    - name: ESLint
      run: pnpm lint --no-cache
      shell: bash

    - name: Typecheck
      run: pnpm typecheck
      shell: bash

    - name: Test
      run: pnpm test --silent
      shell: bash

    - name: Svelte Check
      run: pnpm --filter @xstate/svelte svelte-check
      shell: bash

    - name: Knip
      run: pnpm knip
      shell: bash
