name: 'CI checks'
runs:
  using: 'composite'
  steps:
    - name: Run zizmor
      uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
      with:
        persona: pedantic
        annotations: true
        advanced-security: false

    - name: Build
      run: pnpm build
      shell: bash

    - name: ESLint
      run: pnpm lint --no-cache
      shell: bash

    - name: Typecheck
      run: pnpm typecheck
      shell: bash

    - name: Test
      run: pnpm test --silent
      shell: bash

    - name: Svelte Check
      run: pnpm --filter @xstate/svelte svelte-check
      shell: bash

    - name: Knip
      run: pnpm knip
      shell: bash
