/**
 * `@xstate/test` — model-based and property-based testing for XState, built on
 * fast-check.
 *
 * `import { ... } from '@xstate/test'` is the only import a test file needs.
 *
 * `propertyTest()`, `generateTestSuite()` and `testPaths()` are the
 * fast-check-backed entry points: they build the adapter themselves and take
 * fast-check's options at the top level. Pass `adapter` to use another
 * generator.
 */
export {
  ModelTestFailure,
  PropertyScenarioRunner,
  ReplayNotReproducedError,
  TestCampaignError,
  assertTestCoverage,
  assertTestWeight,
  checkLinearizable,
  createPickDescriptor,
  defaultEquivalent,
  defaultFormatSnapshot,
  deriveCaseSeed,
  describeTestSuite,
  evaluateTestStopCondition,
  formatTestCoverage,
  formatTestCoverageHTML,
  formatTestCoverageId,
  formatTestCoverageJUnit,
  formatTestStatistics,
  formatTestSuiteFixtureTitle,
  formatTestTrace,
  isEventDescriptorObject,
  normalizeEventDescriptors,
  parseTestSuite,
  replayTest,
  replayTestSuite,
  replayTestSuiteFixture,
  runParallelPropertyCommands,
  sampleGenerator,
  serializeTestSuite,
  serializeTestTrace,
  testCoverageToJSON,
  type AnyTestEventDescriptor,
  type DescribeTestSuiteOptions,
  type FormatTestCoverageHTMLOptions,
  type FormatTestCoverageJUnitOptions,
  type FormatTestCoverageOptions,
  type GenerateTestSuiteOptions,
  type LinearizabilityEntry,
  type LinearizabilityModel,
  type LinearizabilityOptions,
  type LinearizabilityResult,
  type NormalizedEventCase,
  type ParallelPropertyCommandsOptions,
  type ParallelPropertyCommandsResult,
  type ParallelPropertySut,
  type ParallelPropertySutSession,
  type PathOptions,
  type PortableTemporalFailure,
  type PortableTestTimelineEntry,
  type PropertyAutoFrontierOptions,
  type PropertyCommandDescriptor,
  type PropertyCommandGenerator,
  type PropertyExecutionConfig,
  type PropertyFrontierContext,
  type PropertyFrontierOptions,
  type PropertyGeneratedCommand,
  type PropertyGenerator,
  type PropertyGeneratorKind,
  type PropertyOptions,
  type PropertySwarmOptions,
  type PropertyTargetFrontierOptions,
  type PropertyTargetObservation,
  type PropertyTestOptions,
  type ReplayTestSuiteOptions,
  type SeededGeneratorKind,
  type TestActorOutcome,
  type TestActorTimelineEntry,
  type TestAdapter,
  type TestAdapterRequest,
  type TestAdapterResult,
  type TestCommand,
  type TestComparedObservation,
  type TestCoverage,
  type TestCoverageDimension,
  type TestCoverageDimensionJSON,
  type TestCoverageJSON,
  type TestCoverageStatus,
  type TestCoverageThresholds,
  type TestEventCaseCounts,
  type TestEventDescriptor,
  type TestEventGenerators,
  type TestEventTimelineEntry,
  type TestExecutionOptions,
  type TestExplorationBounds,
  type TestExplorationFrontier,
  type TestExplorationSeed,
  type TestExplorationSwarm,
  type TestExplorationTarget,
  type TestFailureExtras,
  type TestFailureFormatOptions,
  type TestFailureStore,
  type TestFixture,
  type TestGenerator,
  type TestInvariant,
  type TestInvariantContext,
  type TestLabelCoverage,
  type TestLabelExpectations,
  type TestLabelRecorders,
  type TestMode,
  type TestObservation,
  type TestOptions,
  type TestOutcomeRecord,
  type TestPathGeneratorKind,
  type TestPathRunResult,
  type TestPathsOptions,
  type TestPathsResult,
  type TestPickDescriptor,
  type TestReference,
  type TestReferenceContext,
  type TestReferenceSession,
  type TestReplayMetadata,
  type TestResolvedEventDescriptor,
  type TestRuntimeTimelineEntry,
  type TestStateAssertion,
  type TestStateAssertions,
  type TestStateKey,
  type TestStep,
  type TestStopCondition,
  type TestStopConditionObject,
  type TestStoppedBecause,
  type TestStoredFailure,
  type TestSuite,
  type TestSuiteReplayFailure,
  type TestSuiteReplayResult,
  type TestSut,
  type TestSutCompleteContext,
  type TestSutContext,
  type TestSutDisposeContext,
  type TestSutSendContext,
  type TestSutSession,
  type TestTemporal,
  type TestTemporalCounts,
  type TestTemporalCoverage,
  type TestTemporalPredicate,
  type TestTimelineEntry,
  type TestTrace
} from './engine/index.ts';

export {
  generateTestSuite,
  propertyTest,
  testPaths,
  type FastCheckGenerateTestSuiteOptions,
  type FastCheckPropertyTestOptions,
  type FastCheckTestPathsOptions
} from './propertyTest.ts';
export {
  extractReplayPath,
  fastCheckAdapter,
  type FastCheckAdapterOptions,
  type FastCheckGeneratorKind,
  type FastCheckSchedulerOptions,
  type FastCheckSchedulerReport
} from './adapter.ts';
export { pick } from './pick.ts';
export {
  createFailureDatabase,
  type FailureDatabaseOptions,
  type FailuresOption
} from './failures.ts';
export {
  getCurrentScheduler,
  withScheduledReference,
  withScheduledSut
} from './scheduler.ts';
export {
  arbitraryFromSchema,
  eventsFromSchemas,
  mergeEventGenerators
} from './schema.ts';
export type { EventsFromSchemasOptions, SchemaConverter } from './schema.ts';
