name: Publish

on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {} # each job should define its own permission explicitly

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    permissions:
      contents: write # to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks

      - name: Create or update release pull request
        id: changesets
        # https://github.com/changesets/action
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          version: pnpm run version

  publish:
    name: Publish
    if: needs.version.outputs.hasChangesets == 'false'
    needs: version
    runs-on: ubuntu-latest
    environment: npm
    timeout-minutes: 20
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: pnpm run release
